export const MentorsList = [
    {
        name: 'Megan',
        color: 'green',
        experience: 'Graphic/visual/brand design, Adobe Illustrator/Photoshop, Figma, UI/UX design, print/merch design, simple motion design/animation (After Effects, Photoshop), simple 3D (Cinema 4D)',
        specialty: 'Illustrator, Figma, merch design, cute/brutalist/isometric designs, web design',
        fun: 'DAY6, pH-1, films/shows (any genre!), baking',
        img: '',
        symbol: '1',
        symbolStyling: '',
    },
    {
        name: 'Juna',
        color: 'orange',
        experience: 'Graphic/visual/brand design, illustration, animation, UI/UX design, Adobe Illustrator/Photoshop/Animate, Figma, Procreate, print/merch design, animation',
        specialty: 'Illustrator, Photoshop, Figma, vector illustration, animation, print design',
        fun: 'Genshin Impact c;, Twitter/Instagram artists, Vtubers (NijiEN)',
        img: '',
        symbol: '2',
        symbolStyling: '',
    },
    {
        name: 'Thoa',
        color: 'pink',
        experience: 'Graphic/visual/brand design, illustration, UI/UX design, Figma, Adobe Illustrator/Photoshop, print design, Procreate',
        specialty: 'Visual/UI Design, graphic design, cute Illustrations',
        fun: 'Pokemon, N.Flying, best stationery supplies (pen and mechanical pencil recommendations), journaling, cognitive functions (personality types) & love languages',
        img: '',
        symbol: '3',
        symbolStyling: '',
    },
    {
        name: 'Ricky',
        color: 'green',
        experience: 'Graphic/visual/brand design, Adobe Illustrator/Photoshop/InDesign, Figma, motion design/animation (After Effects), UI/UX design, print design',
        specialty: 'After Effects, Illustrator, Photoshop, vector calligraphy, trendy design style (overlays, textures, gradients)',
        fun: 'Alternative R&B music, Iced Americanos, instant photography, Nintendo, sustainable fashion',
        img: '',
        symbol: '4',
        symbolStyling: '',
    },
    {
        name: 'Leann',
        color: 'pink',
        experience: 'Web design, web development, design systems, visual design, illustration',
        specialty: 'Open source software (Inkscape, Krita, Gimp)',
        fun: 'Minecraft, art, aquariums',
        img: '',
        symbol: '5',
        symbolStyling: '',
    },
    {
        name: 'Meshach',
        color: 'green',
        experience: 'Web development, web design, visual/graphic design, shirt design',
        specialty: 'Web development',
        fun: 'Art, film/tv (Wes Anderson, A24)',
        img: '',
        symbol: '6',
        symbolStyling: '',
    },
    {
        name: 'Sabrina',
        color: 'orange',
        experience: 'UX/UI design, print design, Figma, Adobe Illustrator/Photoshop',
        specialty: 'Graphic design, product design',
        fun: 'Art museums, music concerts, films/tv-shows, doodling, matcha',
        img: '',
        symbol: '7',
        symbolStyling: '',
    },
]